backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Path", name: "path", widget: "string", default: {{slug}}}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "Services"
    label: "Services"
    folder: "src/pages/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services-page"}
      - {label: "Path", name: "path", widget: "string", default: "/services/{{slug}}"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/about-us.md"
        label: "About us"
        name: "about-us"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/about-us"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {
              label: "People", 
              name: "people", 
              widget: "list", 
              fields: [
                {
                  label: "Name", 
                  name: "name", 
                  widget: "string"
                }, 
                {
                  label: "Job title", 
                  name: "jobtitle", 
                  widget: "string"
                }, 
                {
                  label: "Image", 
                  name: "image", 
                  widget: "image"
                }, 
                {
                  label: "Paragraphs", 
                  name: "paragraphs", 
                  widget: "list", 
                  fields: [ 
                    {
                      label: "id", 
                      name: "id", 
                      widget: "string"
                    }, 
                    {
                      label: "text", 
                      name: "text", 
                      widget: "string"
                    }
                  ]
                }
              ]
            }
          - {label: "Why us", name: "whyus", widget: "object", fields: [
            {
              label: "Title",
              name: "title",
              widget: "string"
            },
            {
              label: "Reasons",
              name: "reasons",
              widget: "list",
              fields: [
                {
                  label: "id", 
                  name: "id", 
                  widget: "string"
                }, 
                {
                  label: "text", 
                  name: "text", 
                  widget: "string"
                }
              ]
            }
          ]}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/services.md"
        label: "Services"
        name: "services"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services-home"}
          - {label: "Path", name: "path", widget: "hidden", default: "/services"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {
              label: "Snippets", 
              name: "snippets", 
              widget: "list", 
              fields: [
                {
                  label: "Title", 
                  name: "title", 
                  widget: "string"
                }, 
                {
                  label: "Link URL", 
                  name: "linkUrl", 
                  widget: "string"
                }, 
                {
                  label: "Link text", 
                  name: "linkText", 
                  widget: "string"
                }, 
                {
                  label: "Bullets", 
                  name: "bullets", 
                  widget: "list", 
                  fields: [ 
                    {
                      label: "id", 
                      name: "id", 
                      widget: "string"
                    }, 
                    {
                      label: "text", 
                      name: "text", 
                      widget: "string"
                    }
                  ]
                }
              ]
            }
