backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:

  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Settings"
        file: "_data/settings.json"
        description: "General Site Settings"
        fields:
          - {label: "Global title", name: "siteTitle", widget: "string"}
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - {label: "Global description", name: "siteDescription", widget: "string"}
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields: 
              - {label: "Full company name", name: "fullCompanyName", widget: "string"}
              - {label: "Company number", name: "companyNumber", widget: "string"}
              - {label: "VAT number", name: "vatNumber", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
              - label: "address"
                name: "address"
                widget: "object"
                fields:
                  - {label: "Line 1", name: "line1", widget: "string"}
                  - {label: "Line 2", name: "line2", widget: "string"}
                  - {label: "Town/city", name: "town", widget: "string"}
                  - {label: "County", name: "county", widget: "string"}
                  - {label: "Country", name: "country", widget: "string"}
                  - {label: "Postcode", name: "postcode", widget: "string"}
              - label: "Social media profiles"
                name: "social"
                widget: "list"
                fields: [
                  {
                    label: "Provider Name", 
                    name: "providerName", 
                    widget: "string"
                  },
                  {
                    label: "Provider display name", 
                    name: "providerDisplayName", 
                    widget: "string"
                  },
                  {
                    label: "URL", 
                    name: "url", 
                    widget: "string"
                  },
                  {
                    label: "Profile display name", 
                    name: "profileDisplayName", 
                    widget: "string"
                  }
                ]

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "Services"
    label: "Services"
    folder: "src/pages/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro paragraph", name: "intro", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "Legal"
    label: "Legal"
    folder: "src/pages/legal"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "legal"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home page"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {
              label: "Definition", 
              name: "definition", 
              widget: "list", 
              fields: [
                {
                  label: "Title", 
                  name: "title", 
                  widget: "string"
                }, 
                {
                  label: "Pronunciation", 
                  name: "pronunciation", 
                  widget: "string"
                }, 
                {
                  label: "Description", 
                  name: "description", 
                  widget: "string"
                }
              ]
            }
          - {
              label: "Links", 
              name: "links", 
              widget: "list", 
              fields: [
                {
                  label: "ID", 
                  name: "id", 
                  widget: "number"
                }, 
                {
                  label: "Link URL", 
                  name: "linkUrl", 
                  widget: "string"
                }, 
                {
                  label: "Link text", 
                  name: "linkText", 
                  widget: "string"
                }
              ]
            }
          - {label: "Strapline", name: "strapline", widget: "string"} 
          - {label: "Intro paragraph", name: "introPara", widget: "string"}
      - file: "src/pages/about-us.md"
        label: "About us"
        name: "about-us"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Appears on main navigation?", name: "mainNav", widget: "boolean"}
          - {label: "Order on main navigation", name: "order", widget: "number"}
          - {
              label: "People", 
              name: "people", 
              widget: "list", 
              fields: [
                {
                  label: "Name", 
                  name: "name", 
                  widget: "string"
                }, 
                {
                  label: "Job title", 
                  name: "jobtitle", 
                  widget: "string"
                }, 
                {
                  label: "Image", 
                  name: "image", 
                  widget: "image"
                }, 
                {
                  label: "Paragraphs", 
                  name: "paragraphs", 
                  widget: "list", 
                  fields: [ 
                    {
                      label: "id", 
                      name: "id", 
                      widget: "number"
                    }, 
                    {
                      label: "text", 
                      name: "text", 
                      widget: "string"
                    }
                  ]
                }
              ]
            }
          - {label: "Why us", name: "whyus", widget: "object", fields: [
            {
              label: "Title",
              name: "title",
              widget: "string"
            },
            {
              label: "Preamble",
              name: "preamble",
              widget: "string"
            },
            {
              label: "Reasons",
              name: "reasons",
              widget: "list",
              fields: [
                {
                  label: "id", 
                  name: "id", 
                  widget: "number"
                }, 
                {
                  label: "title", 
                  name: "title", 
                  widget: "string"
                },
                {
                  label: "text", 
                  name: "text", 
                  widget: "string"
                }
              ]
            },
            {
              label: "Postamble",
              name: "postamble",
              widget: "string"
            }
          ]}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/services.md"
        label: "Services"
        name: "services"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services-home"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Appears on main navigation?", name: "mainNav", widget: "boolean"}
          - {label: "Order on main navigation", name: "order", widget: "number"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {
              label: "Snippets", 
              name: "snippets", 
              widget: "list", 
              fields: [
                {
                  label: "Title", 
                  name: "title", 
                  widget: "string"
                }, 
                {
                  label: "Link URL", 
                  name: "linkUrl", 
                  widget: "string"
                }, 
                {
                  label: "Link text", 
                  name: "linkText", 
                  widget: "string"
                }, 
                {
                  label: "Bullets", 
                  name: "bullets", 
                  widget: "list", 
                  fields: [ 
                    {
                      label: "id", 
                      name: "id", 
                      widget: "number"
                    }, 
                    {
                      label: "text", 
                      name: "text", 
                      widget: "string"
                    }
                  ]
                }
              ]
            }
      - file: "src/pages/logistics.md"
        label: "Logistics"
        name: "logistics"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "logistics-home"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Appears on main navigation?", name: "mainNav", widget: "boolean"}
          - {label: "Order on main navigation", name: "order", widget: "number"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {
              label: "Snippets", 
              name: "snippets", 
              widget: "list", 
              fields: [
                {
                  label: "Title", 
                  name: "title", 
                  widget: "string"
                }, 
                {
                  label: "Sections", 
                  name: "sections", 
                  widget: "list", 
                  fields: [ 
                    {
                      label: "id", 
                      name: "id", 
                      widget: "number"
                    }, 
                    {
                      label: "Heading", 
                      name: "heading", 
                      widget: "string"
                    },
                    {
                      label: "Paragraphs", 
                      name: "paragraphs", 
                      widget: "list", 
                      fields: [ 
                        {
                          label: "id", 
                          name: "id", 
                          widget: "number"
                        }, 
                        {
                          label: "text", 
                          name: "text", 
                          widget: "string"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
      - file: "src/pages/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Appears on main navigation?", name: "mainNav", widget: "boolean"}
          - {label: "Order on main navigation", name: "order", widget: "number"}
          - {label: "Body", name: "body", widget: "markdown"}
