backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Path", name: "path", widget: "string", default: {{slug}}}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "Services"
    label: "Services"
    folder: "src/pages/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services-page"}
      - {label: "Path", name: "path", widget: "string" default: "/services/{{slug}}"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/about-us.md"
        label: "About us"
        name: "about-us"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/about-us"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {
              label: "People", 
              name: "people", 
              widget: "list", 
              fields: [
                {
                  label: "Name", 
                  name: "name", 
                  widget: "string"
                }, 
                {
                  label: "Job title", 
                  name: "jobtitle", 
                  widget: "string"
                }, 
                {
                  label: "Image", 
                  name: "image", 
                  widget: "image"
                }, 
                {
                  label: "Paragraphs", 
                  name: "paragraphs", 
                  widget: "list", 
                  fields: [ 
                    {
                      label: "id", 
                      name: "id", 
                      widget: "string"
                    }, 
                    {
                      label: "text", 
                      name: "text", 
                      widget: "string"
                    }
                  ]
                }
              ]
            }
          - {label: "Why us", name: "whyus", widget: "object", fields: [
            {
              label: "Title",
              name: "title",
              widget: "string"
            },
            {
              label: "Reasons",
              name: "reasons",
              widget: "list",
              fields: [
                {
                  label: "id", 
                  name: "id", 
                  widget: "string"
                }, 
                {
                  label: "text", 
                  name: "text", 
                  widget: "string"
                }
              ]
            }
          ]}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/services.md"
        label: "Services"
        name: "services"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services-home"}
          - {label: "Path", name: "path", widget: "hidden", default: "/services"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {
              label: "Snippets", 
              name: "snippets", 
              widget: "list", 
              fields: [
                {
                  label: "Title", 
                  name: "title", 
                  widget: "string"
                }, 
                {
                  label: "Link URL", 
                  name: "linkUrl", 
                  widget: "string"
                }, 
                {
                  label: "Link text", 
                  name: "linkText", 
                  widget: "string"
                }, 
                {
                  label: "Bullets", 
                  name: "bullets", 
                  widget: "list", 
                  fields: [ 
                    {
                      label: "id", 
                      name: "id", 
                      widget: "string"
                    }, 
                    {
                      label: "text", 
                      name: "text", 
                      widget: "string"
                    }
                  ]
                }
              ]
            }
      - file: "src/pages/product/product.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: "Test", name: "test", widget: list, fields: [{label: Title, name: title, widget: text}]}
          - {label: "Path", name: "path", widget: "hidden", default: "/products"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {
            label: Intro, 
            name: intro, 
            widget: object, 
            fields: [
              {
                label: Heading, 
                name: heading, 
                widget: string
              }, 
              {
                label: Description, 
                name: description, 
                widget: text
              }, 
              {
                label: Blurbs, 
                name: blurbs, 
                widget: list, 
                fields: [
                  {
                    label: Image, 
                    name: image, 
                    widget: image
                  }, 
                  {
                    label: Text, 
                    name: text, 
                    widget: text
                  }
                ]
              }
            ]
          }
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
